### ISSUE TITLE
Several tutorial versions

### ISSUE THREAD

**Issue by pierfle** [MiniZinc/minizinc.github.io#13]
Which tutorial & link are current: A 96-page version (http://www.minizinc.org/tutorial/minizinc-tute.pdf) is linked to from http://www.minizinc.org/resources.html, and an 82-page version (http://www.minizinc.org/downloads/doc-latest/minizinc-tute.pdf, mysteriously called "GAGA"!) is linked to from http://www.minizinc.org/index.html.

Note also that the table of contents of the tutorial has page numbers that are off (too low) by 2.  Similarly for the page links from the index at the end.

**Comment by guidotack** [comment]
We are currently preparing an all-new tutorial (basically the same content but slightly updated), which will be available online and as a PDF. This will replace the current version(s).

**Comment by pierfle** [comment]
OK, and is it already known what the official link(s) will be?

**Comment by guidotack** [comment]
A preview is now online. There is a redirect from the following URL to the latest (English) version:
http://www.minizinc.org/doc-latest/index-en.html
In addition, the versioning scheme is as follows:
http://www.minizinc.org/doc-<VERSION>/<LANGUAGE>/index.html

The pages that are currently online will not be the final 2.2.0 release pages, so the permalinks into the documents may still change.

**Comment by pierfle** [comment]
OK, and is there no need to change already now the two links (to two different and other versions) in my initial comment?

**Comment by guidotack** [comment]
Thanks. Fixed.
