### ISSUE TITLE
Broken links to documentation

### ISSUE THREAD

**Issue by jarble** [MiniZinc/minizinc.github.io#16]
Several pages in MiniZinc's documentation (like [this one](https://www.minizinc.org/doc-lib/doc-builtins-enum.html)) appear to be broken. Is it possible to repair these broken links?

**Comment by Dekker1** [comment]
Hi @jarble,

Where did you find this link? It seems to be pointing to the old documentation, but I do not know where this link is located.

If you where interested in the information behind the link, you probably want to have a look here: https://www.minizinc.org/doc-latest/en/lib-builtins.html#functions-for-enums

**Comment by jarble** [comment]
I found the link from a Google search page, so this link was probably working until recently.

**Comment by Dekker1** [comment]
There are currently no plans to do so because the structure has changed too much. Currently the hope is that the search engines will deprecate these results soon.
