### ISSUE TITLE
MiniZincIDE-2.2.3-bundled-setup-win64.exe contains virus

### ISSUE THREAD

**Issue by kuitpo** [MiniZinc/minizinc.github.io#17]
Windows 10 Defender (current of Windows updates and of Defender definitions) gives the subject line message, naming the virus as the trojan Spursint.F!cl , which it deems a severe threat. 

I have not had such a warning since setting up this PC over a year ago, and would be inclined to take this warning quite seriously.

**Comment by guidotack** [comment]
Sorry for the delayed response. We are certain this was a false positive, we could not detect any infection with any of the tools we used.
