### ISSUE TITLE
jobshop.dzn missing

### ISSUE THREAD

**Issue by scoulondre** [MiniZinc/minizinc.github.io#2]
In the tutorial examples tarball... (Tx for the great work)

**Comment by schutta** [comment]
Thanks for reporting. We will add the missing data file, once located.

In the meantime, you can use following data.

```
jobs = 5;
tasks = 5;
d = [| 1, 4, 5, 3, 6 
     | 3, 2, 7, 1, 2
     | 4, 4, 4, 4, 4   
     | 1, 1, 1, 6, 8
     | 7, 3, 2, 2, 1 |]; 
```
