### ISSUE TITLE
Download links inconsistent (broken)

### ISSUE THREAD

**Issue by captainpete** [MiniZinc/minizinc.github.io#3]
Hey!

Trying to download and noticed installer bundles in https://github.com/MiniZinc/MiniZincIDE/releases/ are sometimes named with `bundle` and sometimes `bundled`. The links generated by the site assume `bundled` so some are broken (the main download links on the software page and the sidebar on the main page for the OSX installer).

Oh, and thanks a bunch for the excellent software!

**Comment by guidotack** [comment]
Right, sorry!  It's just the Mac OS packages that were named incorrectly (we recently modified our build system).  Should be fixed now.

**Comment by captainpete** [comment]
Quick reply! Ah the linux ones also look as if they may have the same thing happening? See https://github.com/MiniZinc/MiniZincIDE/releases/

**Comment by guidotack** [comment]
The Linux ones are ok.

**Comment by captainpete** [comment]
Thanks 👍
