### ISSUE TITLE
MacOS requirement out of date

### ISSUE THREAD

**Issue by ridgeworks** [MiniZinc/minizinc.github.io#70]
Contrary to  <https://www.minizinc.org/software.html>  current releases do not run on MacOS 10.12. Installation doc/release notes should reflect actual requirements. (I had to go back to 2.5.5 to find a compatible version for my config.)

I suspect this may be due to qt requirements.

**Comment by cyderize** [comment]
Thanks! Indeed Qt seems to now officially only support macOS 11 and later (although I believe the package actually will work on 10.15+)
