### ISSUE TITLE
Challenge links

### ISSUE THREAD

**Issue by ybarsami** [MiniZinc/minizinc.github.io#74]
Dear MiniZinc team,

Thank you for your project.

1) On the global challenges webpage:

https://www.minizinc.org/challenge/globals/

The link to the previous challenges miss a slash ("/"), e.g. if you click on 2012 you end up on https://www.minizinc.org/challenge2012/ which is a "404 not found", but the correct link would just be https://www.minizinc.org/challenge/2012/

2) On the individual challenge results webpages, for instance on the webpage for 2022:

https://www.minizinc.org/challenge/2022/results/

If you want to download the problem instances, the link has a "/results" too much. For instance on this webpage you end up on https://www.minizinc.org/challenge/2022/results/mznc2022_probs.tar.gz which is a "404 not found", but the correct link would just be https://www.minizinc.org/challenge/2022/mznc2022_probs.tar.gz

The same goes if you try to compute results on individual challenges and then click on the links that are created, there is a "/result" too much (and also we can see a double slash in the link).

Thank you if you have time to fix those issues.

Yann

**Comment by cyderize** [comment]
Thanks for finding these!

I just pushed a fix which should hopefully fix all of those (and should be live in a few minutes).
